name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Short Sha
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short $SHA)" >> "$GITHUB_OUTPUT"
        env:
          SHA: ${{ github.sha }}        
      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: eddsnx3/rpr-connect:latest eddsnx3/rpr-connect:staging