name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: rpr-connect:latest
      
      - name: Inspect
        run: |
          docker image inspect rpr-connect:latest
